version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: shopsphere-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shopsphere
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
  backend:
    build:
      context: ./backend
    container_name: shopsphere-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: shopsphere-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres-data: